config/routes.rb
SampleApp::Application.routes.draw do

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get "users/new"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110203205540
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password

  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex},
                    :uniqueness => true
  #Automatically create the virtual attribute 'password confirmation'
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    return nil if user.nil?
    return user if user.salt == cookie_salt
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :index, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

private

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

  def signed_in?
    !current_user.nil?
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{ :href => "http://news.railstutorial.org/" } News
      %li
        %a{ :href => "http://www.railstutorial.org/" } Rails Tutorial        

app/views/layouts/_header.html.haml
%header
  %a{ :href => root_path }
    = image_tag "logo.png", :alt => "Sample App", :class => "round"
  %nav.round
    %ul
      %li= link_to "Home", root_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)                
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/_stylesheets.html.haml
<!--[if lt IE 9]>
%script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"
<![endif]-->
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'
<!--[if lt IE 8]>
= stylesheet_link_tag 'blueprint/ie'
<![endif]-->
= csrf_meta_tag
= stylesheet_link_tag 'custom', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
  %body
    .container
      = render 'layouts/header'
      %section.round
        - flash.each do |key, value|
          %div{:class => "flash #{key}"}
            = value
        = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?
      = debug(response.status) if Rails.env.development?

app/views/pages/about.html.haml
%h1 About Us
%p
  %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development with
  %a{ :href => "http://rubyonrails.org/"} Ruby on Rails.
  This is the sample application for the tutorial.

app/views/pages/contact.html.haml
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  %a{ :href => "http://railstutorial.org/feedback"} feedback page.

app/views/pages/help.html.haml
%h1
  %p
    Get help on Ruby on Rails Tutorial at the
    %a{ :href => "http://railstutorial.org/help"} Rails Tutorial help page
    To get help on this sample app, see the
    %a{ :href => "http://railstutorial.org/book"} Rails Tutorial book

app/views/pages/home.html.haml
%h1 Sample App
%p
  This is the home page for the
  %a{ :href => "http://railstutorial.org/"} Ruby on Rails Tutorial
  sample application.
= link_to "Sign up now!", signup_path, :class => "signup_button round"

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, 'error')} prohibited this user from being saved:"
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/users/_user.html.haml
%li
  = gravatar_for user, :size => 30
  = link_to user.name, user
  - if current_user.admin?
    | 
    = link_to "delete", user, :method => :delete, :confirm => "You sure?",
                              :title => "Delete #{user.name}"

app/views/users/edit.html.haml
%h1 Edit user
= form_for @user do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :password
    %br
    = f.text_field :password, :type => "password"
  .field
    = f.label :password_confirmation, "Confirmation"
    %br
    = f.text_field :password_confirmation, :type => "password"
  .actions
    = f.submit "Update"
%div
  = gravatar_for @user
  %a{:href => "http://gravatar.com/emails"} change

app/views/users/index.html.haml
%h1 All users

= will_paginate

%ul.users
  = render @users

= will_paginate      

app/views/users/new.html.haml
%h1 Sign up
= form_for @user do |f|
  = render 'shared/error_messages'
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :email
    %br
    = f.text_field :email
  .field
    = f.label :password
    %br
    = f.text_field :password, :type => "password"
  .field
    = f.label :password_confirmation, "Confirmation"
    %br
    = f.text_field :password_confirmation, :type => "password"
  .actions
    = f.submit "Sign up"
    

app/views/users/show.html.haml
%table.profile{ :summary => "Profile information" }
  %tr
    %td.main
      %h1
        = gravatar_for @user
        = @user.name
    %td.sidebar.round
      %strong Name
      = @user.name
      %br
      %strong URL
      = link_to user_path(@user), @user